### ISSUE TITLE
Training produces weird results

### ISSUE THREAD

**Issue by 3f6a** [Shunsuke-1994/rfamgen#5]
I'm trying to follow the instructions in the readme to train a CMVAE model on a different family. I wrote the following script following the instructions in the readme:

https://gist.github.com/3f6a/7c8e844293bf5be4ce51971905ce0cd5

However after running that, I tried to evaluate the sampled sequences with Infernal, and it seems they are very bad. Computing the scores of the sampled sequences with `cmalign` gives very poor scores (worse than random).

Am I doing something wrong with the linked script?

**Comment by Shunsuke-1994** [comment]
Could you give me all files?

**Comment by Shunsuke-1994** [comment]
I tried to apply RfamGen to RF00162, but I couldn't reproduce it.
Rather, I got high bit scores of the generated sequences as shown in the attached figure.
I guess the reason might be epoch number you used.
Anyway, I added my example (`notebooks/trial_RF00162.ipynb`). I hope this would be your help.
![bitscores_hist](https://github.com/user-attachments/assets/ca47a0c1-1379-4e95-8147-35e5078c9051)

Best, 
Shunsuke

**Comment by Shunsuke-1994** [comment]
It seems that you are not saving models. You need to add `--save_ckpt --ckpt_iter` at L32-39.
```
pixi run python scripts/train.py \
--data_dir datasets/$RFAM_FAMILY \
--X_train "$RFAM_FAMILY"_unique_seed_removed_notrunc_traceback_onehot_cm_train.h5 \
--w_train "$RFAM_FAMILY"_unique_seed_removed_notrunc_traceback_onehot_cm_train_weight_threshold0p1.h5 \
--X_valid "$RFAM_FAMILY"_unique_seed_removed_notrunc_traceback_onehot_cm_valid.h5 \
--w_valid "$RFAM_FAMILY"_unique_seed_removed_notrunc_traceback_onehot_cm_valid_weight_threshold0p1.h5 \
--epoch 200 \
--beta 1e-3 --use_anneal --use_early_stopping \
--log --log_dir ./outputs/$RFAM_FAMILY
```

And, you are sampling from a model at epoch 3 at L43.
`--ckpt ./outputs/$RFAM_FAMILY/model_epoch3.pt \`

**Comment by Shunsuke-1994** [comment]
I guess the issued should be solved. 
Let me close.

**Comment by Shunsuke-1994** [comment]
Could you share your dataset and outputs files (config, weights, h5 files, sequences, log etc.) or link of google drive via email(`oolongtea1980[at]gmail.com`) or something? 
Let me check.

**Comment by Shunsuke-1994** [comment]
Thank you for sharing the files, but I’m afraid I can’t reproduce or figure out your problem because the shared files are only outputs.
Can I confirm whether the sequences you used are ones available from here (https://rfam.org/family/RF00162#tabview=tab1)
again?
If I assume the script is unchanged, I guess the reason why your elbo is too low may be comming from too small weights. Although I am not sure if the problem is stemming from your weights, Too small weights likely to happen when the sequences are highly conserved and close to each other. In this case, you need to reduce the threshold of weighting (e.g., 0.1 -> 0.01). , However, RF00162 of RfamDB is highly diverse and weights are unlikely to be close to zero with threshold =0.1. That's why I want to check your training data and weights.
Anyway, I suggest to check your weight.
For more details, [readme](https://github.com/Shunsuke-1994/rfamgen?tab=readme-ov-file#generate-weight) or [this paper](https://www.nature.com/articles/nbt.3769).
Finger crossed.

**Comment by Shunsuke-1994** [comment]
I see.  I am glad to hear it worked.
